spring.application.name=ecommerce-app

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_app
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/ecommerce_db